name: Build paper
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "paper/*.tex"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "paper/*.pdf"
